---
dependencies:
- name: "jenkins"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "0.10.31"
  condition: "jenkins.enabled"
- name: "exposecontroller"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.3.82"
  alias: "expose"
- name: "exposecontroller"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.3.82"
  alias: "cleanup"
- name: "chartmuseum"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.1.2"
  condition: "chartmuseum.enabled"
- name: "nexus"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "0.0.19"
  condition: "nexus.enabled"
- name: "heapster"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "0.2.4"
- name: "monocular"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "0.6.4"
  condition: "monocular.enabled"
- name: "docker-registry"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "1.5.0"
  condition: "docker-registry.enabled"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.3.589"
  alias: "gcactivities"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.3.589"
  alias: "gcpods"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.3.589"
  alias: "gcpreviews"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.3.589"
  condition: "controllerrole.enabled"
  alias: "controllerrole"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.3.589"
  condition: "controllerworkflow.enabled"
  alias: "controllerworkflow"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.3.589"
  condition: "controllerteam.enabled"
  alias: "controllerteam"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.3.589"
  condition: "controllercommitstatus.enabled"
  alias: "controllercommitstatus"
- name: "jx"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.3.589"
  condition: "postinstalljob.enabled"
  alias: "postinstalljob"
