---
dependencies:
- name: "jenkins"
  repository: "http://chartmuseum.build.cd.jenkins-x.io"
  version: "0.10.29"
- name: "exposecontroller"
  repository: "http://chartmuseum.build.cd.jenkins-x.io"
  version: "2.3.71"
  alias: "expose"
- name: "exposecontroller"
  repository: "http://chartmuseum.build.cd.jenkins-x.io"
  version: "2.3.71"
  alias: "cleanup"
- name: "pipelinecontroller"
  repository: "file://pipelinecontroller"
  version: "0.0.1"
  condition: "pipelinecontroller.enabled"
- name: "chartmuseum"
  repository: "http://chartmuseum.build.cd.jenkins-x.io"
  version: "1.1.2"
  condition: "chartmuseum.enabled"
- name: "nexus"
  repository: "http://chartmuseum.build.cd.jenkins-x.io"
  version: "0.0.16"
  condition: "nexus.enabled"
- name: "heapster"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "0.2.4"
- name: "monocular"
  repository: "http://chartmuseum.build.cd.jenkins-x.io"
  version: "0.6.4"
  condition: "monocular.enabled"
- name: "docker-registry"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "1.5.0"
  condition: "docker-registry.enabled"
- name: "jx"
  repository: "http://chartmuseum.build.cd.jenkins-x.io"
  version: "1.3.291"
  alias: "gc-activities"
- name: "jx"
  repository: "http://chartmuseum.build.cd.jenkins-x.io"
  version: "1.3.291"
  alias: "gc-previews"
- name: "jx"
  repository: "http://chartmuseum.build.cd.jenkins-x.io"
  version: "1.3.291"
  condition: "controller-workflow.enabled"
  alias: "controller-workflow"
