dependencies:
  - name: jenkins
    version: 0.10.27
    repository: http://chartmuseum.build.cd.jenkins-x.io
  - name: exposecontroller
    version: 2.3.59
    repository: http://chartmuseum.build.cd.jenkins-x.io
    alias: expose
  - name: exposecontroller
    version: 2.3.59
    repository: http://chartmuseum.build.cd.jenkins-x.io
    alias: cleanup
  - name: pipelinecontroller
    version: 0.0.1
    repository: file://pipelinecontroller
    condition: pipelinecontroller.enabled
  - name: chartmuseum
    version: 0.3.2                                                
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    condition: chartmuseum.enabled
  - name: nexus
    version: 0.0.14
    repository: http://chartmuseum.build.cd.jenkins-x.io
    condition: nexus.enabled
  - name: heapster
    version: 0.2.4
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: monocular
    version: 0.5.1
    repository: http://chartmuseum.build.cd.jenkins-x.io
    condition: monocular.enabled
  - name: docker-registry
    version: 1.0.1
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: jx
    version: 1.3.60
    repository: http://chartmuseum.build.cd.jenkins-x.io
    alias: gc-activities
  - name: jx
    version: 1.3.60
    repository: http://chartmuseum.build.cd.jenkins-x.io
    alias: gc-previews
