{{ if .Values.chartmuseumServiceLink.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-x-chartmuseum
  labels:
    app: chartmuseum
    release: jenkins-x
type: Opaque
data:
{{- range $name, $value := .Values.chartmuseum.env.secret }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}