{{- if .Values.teamRoles.viewer.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: committer
  labels:
    jenkins.io/kind: "EnvironmentRole"
  annotations:
    title: "Committer"
    description: "A committer can write to project resources but cannot add/remove users"
rules:
  - apiGroups:
    - jenkins.io
    resources:
    - "*"
    verbs:
    - list
    - get
    - watch
  - apiGroups:
    - ""
    resources:
    - "*"
    verbs:
    - list
    - get
    - watch
    - create
    - update
    - patch
    - delete
{{- end }}
