{{- if .Values.KanikoSecret }}
apiVersion: v1
data:
  kaniko-secret: {{ .Values.KanikoSecret.Data | b64enc | quote }}
kind: Secret
metadata:
  labels:
    jenkins.io/credentials-type: secretText
  name: kaniko-secret
type: Opaque
{{- end }}
