apiVersion: v1
data:
{{- if .Values.PipelineSecrets.MavenSettingsXML }}
  settings.xml: {{ .Values.PipelineSecrets.MavenSettingsXML | b64enc | quote }}
{{- else }}
  settings.xml: ""
{{- end }}
{{- if .Values.PipelineSecrets.SettingsSecurityXML }}
  settings-security.xml: {{ .Values.PipelineSecrets.MavenSettingsXML | b64enc | quote }}
{{- else }}
  settings-security.xml: ""
{{- end }}
kind: Secret
metadata:
  name: jenkins-maven-settings
type: Opaque
