{{- if .Values.teamRoles.viewer.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team-admin
  labels:
    jenkins.io/kind: "EnvironmentRole"
rules:
  - apiGroups:
    - jenkins.io
    resources:
    - "*"
    verbs:
    - list
    - get
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - "*"
    verbs:
    - list
    - get
    - watch
    - create
    - update
    - patch
    - delete
{{- end }}
