{{- if .Values.teamRoles.viewer.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer
  labels:
    jenkins.io/kind: "EnvironmentRole"
rules:
  - apiGroups:
    - jenkins.io
    resources:
    - "*"
    verbs:
    - list
    - get
    - watch
  - apiGroups:
    - ""
    resources:
    - "*"
    verbs:
    - list
    - get
    - watch
{{- end }}
